// <auto-generated />
namespace SsisSample.Tests.SsisFileBasedDeployment_Output
{
    using global::System;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Resources;
    using global::System.Globalization;
    using global::System.ComponentModel;
    using global::System.CodeDom.Compiler;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    internal class Resources
    {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("SsisSample.Tests.SsisFileBasedDeployment_Output.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;TestManifest failOnServerPublishFailureExpression=&quot;False&quot; testSuiteId=&quot;16db26af-28f6-4959-ace5-786b48a985d4&quot; testSuiteName=&quot;SsisFileBasedDeployment&quot; testGroupId=&quot;303e2924-4bbd-4640-86da-bd24967aad36&quot; testGroupName=&quot;SsisFileBasedDeployment&quot; isSingleGroupMode=&quot;True&quot;&gt;&lt;Keys&gt;&lt;Key key=&quot;TestSuiteRevision&quot; value=&quot;13&quot; /&gt;&lt;/Keys&gt;&lt;MethodAssociations&gt;&lt;MethodAssociation methodName=&quot;RunPackage&quot; testName=&quot;RunPackage&quot; testUniqueId=&quot;452f8682-7529-406f-a676-7a6718a48050&quot; /&gt;&lt;/MethodAssoc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestManifest_SsisFileBasedDeployment_303e29244bbd464086dabd24967aad36
        {
            get
            {
                return ResourceManager.GetString("TestManifest_SsisFileBasedDeployment_303e29244bbd464086dabd24967aad36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FileSystemObject fullPath=&quot;C:\Users\Administrator\source\repos\SentryOneTestSamples\SsisSample\EmptyPackage.dtsx&quot; packageProtectionLevel=&quot;EncryptSensitiveWithUserKey&quot; password=&quot;&quot; name=&quot;EmptyPackage.dtsx&quot; size=&quot;0&quot; type=&quot;File&quot; dateCreated=&quot;2019-02-14T19:48:50.0203707Z&quot; dateModified=&quot;2019-02-14T19:48:50.0203707Z&quot; connectionString=&quot;&quot; originalSource=&quot;C:\Users\Administrator\source\repos\SentryOneTestSamples\SsisSample\EmptyPackage.dtsx&quot; location=&quot;FileSystem&quot; sqlServerVersion=&quot;Sql2016&quot; /&gt;.
        /// </summary>
        internal static string TestResource_EmptyPackage_56af6c9fada049d889aab741b9c7b300
        {
            get
            {
                return ResourceManager.GetString("TestResource_EmptyPackage_56af6c9fada049d889aab741b9c7b300", resourceCulture);
            }
        }
    }
}

