// <auto-generated />
namespace WideWorldImporters.Tests.DataDriven_Output
{
    using global::System;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Resources;
    using global::System.Globalization;
    using global::System.ComponentModel;
    using global::System.CodeDom.Compiler;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    internal class Resources
    {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("WideWorldImporters.Tests.DataDriven_Output.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;TestManifest failOnServerPublishFailureExpression=&quot;True&quot; testSuiteId=&quot;d5acb37e-d4a5-4223-aac2-4b51eecf7137&quot; testSuiteName=&quot;DataDriven&quot; testGroupId=&quot;98221a43-9f31-4da4-ac08-a147228a6e8f&quot; testGroupName=&quot;DataDriven&quot; isSingleGroupMode=&quot;True&quot; publishUrl=&quot;http://localhost:44320&quot;&gt;&lt;Keys&gt;&lt;Key key=&quot;TestSuiteRevision&quot; value=&quot;6&quot; /&gt;&lt;/Keys&gt;&lt;MethodAssociations&gt;&lt;MethodAssociation methodName=&quot;ComparisonTest&quot; testName=&quot;Comparison Test&quot; testUniqueId=&quot;6066c5b3-22a6-45ec-9e8a-9c55e03218d6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestManifest_DataDriven_98221a439f314da4ac08a147228a6e8f
        {
            get
            {
                return ResourceManager.GetString("TestManifest_DataDriven_98221a439f314da4ac08a147228a6e8f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	&apos;{{CommonTableName}}&apos; AS TableName, 
        ///	COUNT(*) - 1 AS RecordCount
        ///FROM {{RightTableName}}
        ///WHERE GETDATE() BETWEEN [Valid From] AND [Valid To].
        /// </summary>
        internal static string TestResource_ActualQuery_270ed289b1ec49afba87670be1c472d4
        {
            get
            {
                return ResourceManager.GetString("TestResource_ActualQuery_270ed289b1ec49afba87670be1c472d4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_ComparisonManifest_ee6bb7410c014fc4a6a7a86387aef848
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_ComparisonManifest_ee6bb7410c014fc4a6a7a86387aef848", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	&apos;{{CommonTableName}}&apos; AS TableName, 
        ///	COUNT(*) AS RecordCount 
        ///FROM {{LeftTableName}} .
        /// </summary>
        internal static string TestResource_ExpectedQuery_230795630c2d4ec59aa488b016a72657
        {
            get
            {
                return ResourceManager.GetString("TestResource_ExpectedQuery_230795630c2d4ec59aa488b016a72657", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_TablesForRowCountComparison_8f85ac9f740b45b89326c911edf0fb90
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_TablesForRowCountComparison_8f85ac9f740b45b89326c911edf0fb90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_WideWorldImporters_41e6c71419f7453cbf0c35f50ab94707
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_WideWorldImporters_41e6c71419f7453cbf0c35f50ab94707", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_WideWorldImportersDW_9e990a18f179475e9a24eca7ef66ba76
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_WideWorldImportersDW_9e990a18f179475e9a24eca7ef66ba76", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}

