// <auto-generated />
namespace LegiTestProject1.SsisProjectBasedDeployment_Output
{
    using global::System;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Resources;
    using global::System.Globalization;
    using global::System.ComponentModel;
    using global::System.CodeDom.Compiler;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    internal class Resources
    {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("LegiTestProject1.SsisProjectBasedDeployment_Output.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;TestManifest failOnServerPublishFailureExpression=&quot;False&quot; testSuiteId=&quot;6b801d75-7762-4065-818d-4bd461ca90d0&quot; testSuiteName=&quot;SsisProjectBasedDeployment&quot; testGroupId=&quot;f1ee1265-4312-45c5-8409-6308ec3b8b4a&quot; testGroupName=&quot;SsisProjectBasedDeployment&quot; isSingleGroupMode=&quot;True&quot;&gt;&lt;Keys&gt;&lt;Key key=&quot;TestSuiteRevision&quot; value=&quot;7&quot; /&gt;&lt;/Keys&gt;&lt;MethodAssociations&gt;&lt;MethodAssociation methodName=&quot;RunPackage&quot; testName=&quot;RunPackage&quot; testUniqueId=&quot;62271cfa-805a-4036-b077-a3a014b6cc47&quot; /&gt;&lt;/Method [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestManifest_SsisProjectBasedDeployment_f1ee1265431245c584096308ec3b8b4a
        {
            get
            {
                return ResourceManager.GetString("TestManifest_SsisProjectBasedDeployment_f1ee1265431245c584096308ec3b8b4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FileSystemObject fullPath=&quot;EmptyPackage.dtsx&quot; packageProtectionLevel=&quot;Unknown&quot; password=&quot;&quot; name=&quot;EmptyPackage.dtsx&quot; size=&quot;0&quot; type=&quot;File&quot; dateCreated=&quot;0001-01-01T00:00:00.0000000Z&quot; dateModified=&quot;0001-01-01T00:00:00.0000000Z&quot; connectionString=&quot;&quot; originalSource=&quot;C:\Users\Administrator\source\repos\SentryOneTestSamples\SsisSample\bin\Development\SsisSample.ispac&quot; location=&quot;CompiledProject&quot; sqlServerVersion=&quot;Sql2016&quot; /&gt;.
        /// </summary>
        internal static string TestResource_ispacEmptyPackage_56af6c9fada049d889aab741b9c7b300
        {
            get
            {
                return ResourceManager.GetString("TestResource_ispacEmptyPackage_56af6c9fada049d889aab741b9c7b300", resourceCulture);
            }
        }
    }
}

